use telarex_core::command::Command as CoreCommand;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum UIAction {
    Core(CoreCommand),
    NewTab,
    CloseTab,
    NextTab,
    PrevTab,
    ToggleExplorer,
    EnterCommandMode,
    EnterSearchMode,
    ExitMode,
    ExecuteSearch,
    SelectSearchResult,
    TriggerAutocomplete,
    ToggleMacroPalette,
    StartRecordingMacro(String),
    StopRecordingMacro,
    PlayMacro(String),
    SplitVertical,
    SplitHorizontal,
    FocusLeft,
    FocusRight,
    FocusUp,
    FocusDown,
    SwitchFocus,
    EnterWindowMode,
    ClosePane,
    LeaveWorkspace,
    DisconnectNetwork,
    PromptShareWorkspace,
    Copy,
    Paste,
    Quit,
}
